#ifndef TAGSHTML5_H
#define TAGSHTML5_H

#define INFO //!< This file defines the constants to identify the type of the HTML5 tag.<br>These constants are defined as in the Gumbo library for consistency.

#define HTML5 5 //!< Any number will do. This is just to differentiate from other HTML versions contemplated in previous versions

#define HTML_NO_TAG (-1)  //!< Indicates that a label does not correspond to any accepted HTML5 tag

#define HTML5_HTML		0 // html
#define HTML5_HEAD              1 // head
#define HTML5_TITLE             2 // title
#define HTML5_BASE              3 // base
#define HTML5_LINK              4 // link
#define HTML5_META              5 // meta
#define HTML5_STYLE             6 // style
#define HTML5_SCRIPT            7 // script
#define HTML5_NOSCRIPT          8 // noscript
#define HTML5_TEMPLATE          9 // template
#define HTML5_BODY             10 // body
#define HTML5_ARTICLE          11 // article
#define HTML5_SECTION          12 // section
#define HTML5_NAV              13 // nav
#define HTML5_ASIDE            14 // aside
#define HTML5_H1               15 // h1
#define HTML5_H2               16 // h2
#define HTML5_H3               17 // h3
#define HTML5_H4               18 // h4
#define HTML5_H5               19 // h5
#define HTML5_H6               20 // h6
#define HTML5_HGROUP           21 // hgroup
#define HTML5_HEADER           22 // header
#define HTML5_FOOTER	       23 // foter
#define HTML5_ADDRESS          24 // address
#define HTML5_P                25 // p
#define HTML5_HR               26 // hr
#define HTML5_PRE              27 // pre
#define HTML5_BLOCKQUOTE       28 // blockquote
#define HTML5_OL               29 // ol
#define HTML5_UL               30 // ul
#define HTML5_LI               31 // li
#define HTML5_DL               32 // dl
#define HTML5_DT               33 // dt
#define HTML5_DD               34 // dd
#define HTML5_FIGURE           35 // figure
#define HTML5_FIGCAPTION       36 // figcaption
#define HTML5_MAIN	       37 // main
#define HTML5_DIV              38 // div
#define HTML5_A                39 // a
#define HTML5_EM               40 // em
#define HTML5_STRONG           41 // strong
#define HTML5_SMALL            42 // small
#define HTML5_S                43 // s
#define HTML5_CITE             44 // cite
#define HTML5_Q                45 // q
#define HTML5_DFN              46 // dfn
#define HTML5_ABBR             47 // abbr
#define HTML5_DATA             48 // data
#define HTML5_TIME             49 // time
#define HTML5_CODE             50 // code
#define HTML5_VAR              51 // var
#define HTML5_SAMP             52 // samp
#define HTML5_KBD              53 // kbd
#define HTML5_SUB              54 // sub
#define HTML5_SUP              55 // sup
#define HTML5_I                56 // i
#define HTML5_B                57 // b
#define HTML5_U                58 // u
#define HTML5_MARK             59 // mark
#define HTML5_RUBY             60 // ruby
#define HTML5_RT               61 // rt
#define HTML5_RP               62 // rp
#define HTML5_BDI              63 // bdi
#define HTML5_BDO              64 // bdo
#define HTML5_SPAN             65 // span
#define HTML5_BR               66 // br
#define HTML5_WBR              67 // wbr
#define HTML5_INS              68 // ins
#define HTML5_DEL              69 // del
#define HTML5_IMAGE            70 // image
#define HTML5_IMG              71 // img
#define HTML5_IFRAME           72 // iframe
#define HTML5_EMBED            73 // embed
#define HTML5_OBJECT           74 // object
#define HTML5_PARAM            75 // param
#define HTML5_VIDEO            76 // video
#define HTML5_AUDIO            77 // audio
#define HTML5_SOURCE           78 // source
#define HTML5_TRACK            79 // track
#define HTML5_CANVAS           80 // canvas
#define HTML5_MAP              81 // map
#define HTML5_AREA             82 // area
#define HTML5_MATH             83 // math
#define HTML5_MI               84 // mi
#define HTML5_MO               85 // mo
#define HTML5_MN               86 // mn
#define HTML5_MS               87 // ms
#define HTML5_MTEXT            88 // mtext
#define HTML5_MGLYPH           89 // mglyph
#define HTML5_MALIGNMARK       90 // malignmark
#define HTML5_ANNOTATION_XML   91 // annotation_xml
#define HTML5_SVG              92 // svg
#define HTML5_FOREIGNOBJECT    93 // foreignobject
#define HTML5_DESC             94 // desc
#define HTML5_TABLE            95 // table
#define HTML5_CAPTION          96 // caption
#define HTML5_COLGROUP         97 // colgroup
#define HTML5_COL              98 // col
#define HTML5_TBODY            99 // tbody
#define HTML5_THEAD           100 // thead
#define HTML5_TFOOT           101 // tfoot
#define HTML5_TR              102 // tr
#define HTML5_TD              103 // td
#define HTML5_TH              104 // th
#define HTML5_FORM            105 // form
#define HTML5_FIELDSET        106 // fieldset
#define HTML5_LEGEND          107 // legend
#define HTML5_LABEL	      108 // label
#define HTML5_INPUT           109 // input
#define HTML5_BUTTON          110 // button
#define HTML5_SELECT          111 // select
#define HTML5_DATALIST        112 // datalist
#define HTML5_OPTGROUP        113 // optgroup
#define HTML5_OPTION          114 // option
#define HTML5_TEXTAREA        115 // textarea
#define HTML5_KEYGEN          116 // keygen
#define HTML5_OUTPUT          117 // output
#define HTML5_PROGRESS        118 // progress
#define HTML5_METER           119 // meter
#define HTML5_DETAILS         120 // details
#define HTML5_SUMMARY         121 // summary
#define HTML5_MENU            122 // menu
#define HTML5_MENUITEM	      123 // menuitem
#define HTML5_APPLET          124 // applet
#define HTML5_ACRONYM         125 // acronym
#define HTML5_BGSOUND         126 // bgsound
#define HTML5_DIR             127 // dir
#define HTML5_FRAME           128 // frame
#define HTML5_FRAMESET        129 // frameset
#define HTML5_NOFRAMES        130 // noframes
#define HTML5_ISINDEX         131 // isindex
#define HTML5_LISTING         132 // listing
#define HTML5_XMP             133 // xmp
#define HTML5_NEXTID          134 // nextid
#define HTML5_NOEMBED         135 // noembed
#define HTML5_PLAINTEXT       136 // plaintext
#define HTML5_RB              137 // rb
#define HTML5_STRIKE          138 // strike
#define HTML5_BASEFONT        139 // basefont
#define HTML5_BIG             140 // big
#define HTML5_BLINK           141 // blink
#define HTML5_CENTER          142 // center
#define HTML5_FONT            143 // font
#define HTML5_MARQUEE         144 // marquee
#define HTML5_MULTICOL        145 // multicol
#define HTML5_NOBR            146 // nobr
#define HTML5_SPACER          147 // spacer
#define HTML5_TT              148 // tt
#define HTML5_UNKNOWN         149 // unknown
#define HTML5_LAST            150 // last

#define NUMTAGS_HTML5  151 //!< The current number of tags accepted by the W3C for HTML5

#endif
